version: '3'
services:
  python:
    build:
      context: docker/python
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    env_file:
      - docker/python/.env
    ports:
      - "127.0.0.1:${JP_PORT}:${JP_PORT}"
    volumes:
      - ./python/data:/home/${USER_NAME}/project/data
      - ./python/source:/home/${USER_NAME}/project/source
    command: [
      "pipenv", "run", 
      "jupyter", "lab", 
      "--ip", "0.0.0.0",
      "--port", "${JP_PORT}", 
      "--no-browser"
    ]
